name: azalea
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numba>=0.56
  - numpy>=1.23
  - pytorch-cpu>=1.12
  - pyyaml>=6.0
  - scipy>=1.8
  - click>=8.0
  - mkl
  - tensorflow>=2.10
  - tensorboard>=2.10
  - tensorboardX>=2.5
  - smart_open>=6.0