# name: azalea
# channels:
# - conda-forge
# - pytorch
# - defaults
# dependencies:
# - python=3.6
# - dataclasses=0.6.*
# - typing_extensions=3.7.*
# - cython=0.29.*
# - numba=0.42.*
# - numpy=1.16.*
# - pandas=0.23.*
# - pytorch=1.0.1
# - cudatoolkit=9.0.*
# #- cudatoolkit=10.0.*
# - pyyaml=3.13.*
# - scipy=1.2.*
# - click=7.*
# - mkl=2019.*
# - tensorboardX=1.6.*
# - smart_open=1.8.*
# - pip:
#   - tensorflow==1.12.*
#   - tensorboard==1.12.*



name: azalea
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - dataclasses=0.6  # Only required for Python < 3.7; can be removed for Python >= 3.10
  - typing-extensions>=4.4
  - cython>=0.29.36
  - numba>=0.56
  - numpy>=1.23
  - pandas>=1.3
  - pytorch>=2.0
  - cudatoolkit=11.7  # Updated for CUDA compatibility with modern PyTorch
  - pyyaml>=6.0
  - scipy>=1.9
  - click>=8.0
  - mkl
  - tensorboardX>=2.5
  - smart_open>=6.0
  - pip:
      - tensorflow>=2.10
      - tensorboard>=2.10